[platformio]
default_envs =
  ## An-Penta

  # An-Penta-Mini
  ;an_penta_mini

  # An-Penta-Plus
  ;an_penta_plus

  # An-Penta-Deca
  ;an_penta_deca


  ## Dig-Octa

  #Dig-Octa with Ethernet
  ;dig-Octa_32-8L-ETHON-SR

  #Dig-Octa with Ethernet & temperature sensor
  ;dig-Octa_32-8L-ETHON-SR-Temp


  ## Dig-Quad

  #Dig-Quad V3 with QuinLED-ESP32-ABE (ethernet module)
  ;dig-Quad-V3-ETHON

  #Dig-Quad V3 with QuinLED-ESP32-ABE (ethernet module) & temperature sensor installed
  ;dig-Quad-V3-ETHON-Temp

  #Dig-Quad V3 with QuinLED-ESP32-AB (Antenna onBoard) or QuinLED-ESP32-AE (Antenna External)
  ;dig-Quad-V3

  #Dig-Quad V3 with QuinLED-ESP32-AB (Antenna onBoard) or QuinLED-ESP32-AE (Antenna External) & temperature sensor installed
  ;dig-Quad-V3-Temp

  #Dig-Quad V3 with QuinLED-ESP32-AE+ Full (Touch button, IR and 3 outputs & mic)
  ;dig-Quad-V3-AEplus-full

  #Dig-Quad V3 with QuinLED-ESP32-AE+ Full (Touch button, IR and 3 outputs & mic) & temperature sensor installed
  ;dig-Quad-V3-AEplus-full-Temp


  ## Dig-Uno

  #Dig-Uno V3 with QuinLED-ESP32-AB (Antenna onBoard) or QuinLED-ESP32-AE (Antenna External)
  quinled_diguno

  #Dig-Uno V3 with QuinLED-ESP32-ABE (ethernet module)
  quinled_diguno_eth

  #Dig-Uno V3 with QuinLED-ESP32-AB (Antenna onBoard) or QuinLED-ESP32-AE (Antenna External) & temperature sensor installed
  quinled_diguno_temp

  #Dig-Uno V3 with QuinLED-ESP32-ABE (ethernet module) & temperature sensor installed
  quinled_diguno_eth_temp

  #Dig-Uno V3 with QuinLED-ESP32-AE+ Full (Touch button, IR and 3 outputs & mic)
  ;quinled_diguno_aeplus

  #Dig-Uno V3 with QuinLED-ESP32-AE+ Full (Touch button, IR and 3 outputs & mic) & temperature sensor installed
  ;quinled_diguno_aeplus_tmp


  ## Dig2Go
  quinled_dig2go


  ## Other boards

  # Lilygo T7 S3 for MOONHUB75
  lilygo_t7_s3_moonhub75

  # Adafruit Matrix Portal S3
  adafruit_matrix_portal_s3

  # Ai Thinker ESP32-A1S Audio Kit as a dedicated audio sender
  esp32-a1s_audio_sender


###############
### GLOBALS ###
###############

[treyturner]
build_flags =
  -D SR_ENABLE_DEFAULT
  -D AUTOSAVE_AFTER_SEC=0         ;; disable autosave by default
  -D WLEDMM_WIFI_POWERON_HACK     ;; allow wifi sleep
  -D WLED_AP_SSID_UNIQUE
  -D WLED_WATCHDOG_TIMEOUT=0 -D CONFIG_ASYNC_TCP_USE_WDT=0
  -D WLED_DISABLE_BROWNOUT_DET
  -D CONFIG_ASYNC_TCP_STACK_SIZE=9472  ;; WLEDMM increase stack by 1.25Kb, as audioreactive needs bigger SETTINGS_STACK_BUF_SIZE
  -D ENCODER_CLK_PIN=-1 -D ENCODER_DT_PIN=-1 -D ENCODER_SW_PIN=-1    ;; no default rotary pins
  -D IRTYPE=0                     ;; user needs to set remote type
  !python -c "import os; print(\"-D CLIENT_SSID='\\\"{}\\\"'\".format(os.getenv('IOT_SSID', 'Your_Network')))"
  !python -c "import os; print(\"-D CLIENT_PASS='\\\"{}\\\"'\".format(os.getenv('WPA_KEY', '')))"
  -D WLED_ENABLE_PIXELFORGE
  -D USERMOD_FASTLED              ;; enable not-for-profit effects

build_flags_serial_to_usb =             ;; for Serial-to-USB chip
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_USB_DFU_ON_BOOT=0

build_flags_hardware_cdc =              ;; for Hardware-CDC USB mode
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_USB_DFU_ON_BOOT=1

build_flags_psram =
  -D BOARD_HAS_PSRAM
  -D WLED_USE_PSRAM
  -D WLED_USE_PSRAM_JSON
  -D ALL_JSON_TO_PSRAM                  ;; force all JSON stuff into PSRAM; gives more free heap
  ;-DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1    ;; optional - seems to move more buffers into PSRAM

build_flags_hub75 =
  ${common_mm.HUB75_build_flags}
  ;-D JSON_BUFFER_SIZE=18432            ;; default 54000
  -D MIN_HEAP_SIZE=6144                 ;; default 8192
  -D MAX_SEGMENT_DATA=40960             ;; default 32767
  -D DEFAULT_LED_TYPE=101
  -D LEDPIN=14 -D RLYPIN=-1 -D AUDIOPIN=-1      ;; defaults that avoid pin conflicts with HUB75
  -D WLED_DISABLE_ADALIGHT -D WLED_DISABLE_ALEXA -D WLED_DISABLE_ESPNOW  ;; common_mm.build_disable_sync_interfaces but with infrared omitted
  -D WLED_DISABLE_HUESYNC -D WLED_DISABLE_LOXONE -D WLED_DISABLE_MQTT

build_flags_skip_ir = -D WLED_DISABLE_INFRARED -D _IR_ENABLE_DEFAULT_=false -D IRPIN=-1

## build unflags
build_unflags_dmx = ${common_mm.DMXin_build_flags}
build_unflags_temp = -D USERMOD_DALLASTEMPERATURE -D TEMPERATURE_PIN
build_unflags_skip_ir = -D _IR_ENABLE_DEFAULT_=true

## lib ignores
lib_ignore_temp = paulstoffregen/OneWire
lib_ignore_ir = IRremoteESP8266
lib_ignore_dmx = esp_dmx


[quinboards]
build_flags_diguno_common =
  -D WLED_BRAND='"QuinLED"'
  -D ABL_MILLIAMPS_DEFAULT=1250               ;; max amps from usb
  -D DATA_PINS=16,3 -D PIXEL_COUNTS=30,30     ;; two data pins
  -D BTNPIN=0                                 ;; onboard button
  -D RLYPIN=-1                                ;; no relay
  -D AUDIOPIN=36                              ;; analog audio
  -D I2S_CKPIN=-1 -D I2S_WSPIN=-1 -D I2S_SDPIN=-1 -D MCLK_PIN=-1 ;; no i2s
  -D HW_PIN_SDA=-1 -D HW_PIN_SCL=-1           ;; no i2c
  -D SR_DMTYPE=254                            ;; network audio
  -D SR_FREQ_PROF=1 -D SR_GAIN=37 -D SR_SQUELCH=10
  ${treyturner.build_flags_skip_ir}           ;; no infrared

build_flags_temp = -D TEMPERATURE_PIN=13 -D USERMOD_DALLASTEMPERATURE_MEASUREMENT_INTERVAL=10000
build_flags_ethernet = -D WLED_USE_ETHERNET -D WLED_ETH_DEFAULT=4
build_flags_octa = -D WLED_USE_ETHERNET -D WLED_ETH_DEFAULT=8

build_unflags_diguno_common =
  ${esp32_4MB_V4_M_base.build_unflags}
  -D LEDPIN
  ${common_mm.HUB75_build_flags}        ;; not feasible on diguno
  ${treyturner.build_unflags_skip_ir}   ;; no infrared
  ;-D ARDUINO_USB_CDC_ON_BOOT=1         ;; uncomment if output is spammy


#####################
### BOARD CONFIGS ###
#####################

[env:quinled_dig2go]
extends = esp32_4MB_V4_M_base
platform = ${esp32.platform}            ;; "V4" tasmota
board_build.partitions = ${esp32.default_partitions}
platform_packages = ${esp32.platform_packages}

build_flags =
  ${esp32_4MB_V4_M_base.esp32_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  -D WLED_BRAND='"QuinLED"'
  -D WLED_RELEASE_NAME='QuinLED Dig2go MM'
  -D SERVERNAME='"QuinLED-Dig2go"'
  -D ABL_MILLIAMPS_DEFAULT=3000         ;; dig2go max amps
  -D LEDPIN=16 -D PIXEL_COUNTS=30       ;; one data pin
  -D BTNPIN=0                           ;; onboard button
  -D IRPIN=5                            ;; infrared receiver
  -D RLYPIN=12                          ;; onboard relay
  -D SR_DMTYPE=1                        ;; onboard I2S mic
  -D SR_FREQ_PROF=0 -D SR_GAIN=30 -D SR_SQUELCH=10
  -D I2S_CKPIN=18 -D I2S_WSPIN=4 -D I2S_SDPIN=19 -D MCLK_PIN=-1
  -D HW_PIN_SDA=21 -D HW_PIN_SCL=22     ;; optional I2C header pins

build_unflags =
  ${esp32_4MB_V4_M_base.build_unflags}
  ${common_mm.HUB75_build_flags}        ;; not feasible on dig2go
  ${treyturner.build_unflags_temp}      ;; no onboard temp sensor
  ;-D ARDUINO_USB_CDC_ON_BOOT=1         ;; uncomment if output is spammy
  -D WLED_DISABLE_INFRARED              ;; uncomment if ir isn't included for some reason

lib_deps = ${esp32_4MB_V4_M_base.esp32_lib_deps}

lib_ignore =
  ${common_mm.HUB75_lib_ignore}         ;; not feasible on dig2go
  ${treyturner.lib_ignore_temp}         ;; no onboard temperature sensor


[env:quinled_diguno]
extends = esp32_4MB_V4_M_base
platform = ${esp32.platform}            ;; "V4" tasmota
board_build.partitions = ${esp32.default_partitions}
platform_packages = ${esp32.platform_packages}

build_flags =
  ${esp32_4MB_V4_M_base.esp32_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${quinboards.build_flags_diguno_common}
  -D WLED_RELEASE_NAME='QuinLED DigUno MM'
  -D SERVERNAME='"QuinLED-DigUno"'

build_unflags =
  ${quinboards.build_unflags_diguno_common}
  ${treyturner.build_unflags_temp}      ;; no temperature sensor

lib_deps = ${esp32_4MB_V4_M_base.esp32_lib_deps}

lib_ignore =
  ${common_mm.HUB75_lib_ignore}         ;; not feasible on diguno
  ${treyturner.lib_ignore_temp}         ;; no temperature sensor


[env:quinled_diguno_temp]
extends = esp32_4MB_V4_M_base
platform = ${esp32.platform}            ;; "V4" tasmota
board_build.partitions = ${esp32.default_partitions}
platform_packages = ${esp32.platform_packages}

build_flags =
  ${esp32_4MB_V4_M_base.esp32_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${quinboards.build_flags_diguno_common}
  -D WLED_RELEASE_NAME='QuinLED DigUno Temp MM'
  -D SERVERNAME='"QuinLED-DigUno-Temp"'
  ${quinboards.build_flags_temp}      ;; onboard temperature sensor

build_unflags = ${quinboards.build_unflags_diguno_common}
lib_deps = ${esp32_4MB_V4_M_base.esp32_lib_deps}
lib_ignore = ${common_mm.HUB75_lib_ignore}         ;; not feasible on diguno


[env:quinled_diguno_eth]
extends = esp32_4MB_V4_M_base
platform = ${esp32.platform}            ;; "V4" tasmota
board_build.partitions = ${esp32.default_partitions}
platform_packages = ${esp32.platform_packages}

build_flags =
  ${esp32_4MB_V4_M_base.esp32_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${quinboards.build_flags_diguno_common}
  -D WLED_RELEASE_NAME='QuinLED DigUno Eth MM'
  -D SERVERNAME='"QuinLED-DigUno-Eth"'
  ${quinboards.build_flags_ethernet}  ;; onboard ethernet

build_unflags =
  ${quinboards.build_unflags_diguno_common}
  ${treyturner.build_unflags_temp}      ;; no temperature sensor

lib_deps = ${esp32_4MB_V4_M_base.esp32_lib_deps}

lib_ignore =
  ${common_mm.HUB75_lib_ignore}         ;; not feasible on diguno
  ${treyturner.lib_ignore_temp}         ;; no temperature sensor


[env:quinled_diguno_eth_temp]
extends = esp32_4MB_V4_M_base
platform = ${esp32.platform}            ;; "V4" tasmota
board_build.partitions = ${esp32.default_partitions}
platform_packages = ${esp32.platform_packages}

build_flags =
  ${esp32_4MB_V4_M_base.esp32_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${quinboards.build_flags_diguno_common}
  -D WLED_RELEASE_NAME='QuinLED DigUno Eth Temp MM'
  -D SERVERNAME='"QuinLED-DigUno-Eth-Temp"'
  ${quinboards.build_flags_temp}      ;; onboard temperature sensor
  ${quinboards.build_flags_ethernet}  ;; onboard ethernet

build_unflags = ${quinboards.build_unflags_diguno_common}
lib_deps = ${esp32_4MB_V4_M_base.esp32_lib_deps}
lib_ignore =
  ${common_mm.HUB75_lib_ignore}         ;; not feasible on diguno
  ${treyturner.lib_ignore_ir}


[env:lilygo_t7_s3_moonhub75]
extends = env:esp32S3_8MB_PSRAM_M
platform = ${esp32.platformV4}          ;; uses standard espressif platform instead of tasmota
platform_packages = ${esp32.platformV4_packages}
board = lilygo-t7-s3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

build_flags =
  ${common.build_flags} ${esp32s3.build_flags} -Wno-misleading-indentation -Wno-format-truncation
  ${common_mm.build_flags_S} ${common_mm.build_flags_M}
  ${Speed_Flags.build_flags_V4}         ;; optimize for speed
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  -D WLED_BRAND='"Lilygo"'
  -D WLED_RELEASE_NAME='Lilygo T7 S3 MOONHUB75 MM'
  -D SERVERNAME='"Lilygo-T7-S3-MOONHUB75"'
  ${treyturner.build_flags_hub75}       ;; enable HUB75
  ${treyturner.build_flags_psram}       ;; enable PSRAM
  -D MOONHUB_S3_PINOUT                  ;; MOONHUB75 pinout
  -D I2S_SDPIN=10 -D I2S_CKPIN=11 -D I2S_WSPIN=12 -D MCLK_PIN=-1  ;; hub75 driver
  -D USERMOD_BATTERY -D USERMOD_BATTERY_MEASUREMENT_PIN=2  ;; battery support
  -D STATUSLED=17                       ;; onboard LED
  -D BTNPIN=0                           ;; onboard button
  ${treyturner.build_flags_skip_ir}     ;; no infrared
  -D SR_DMTYPE=254                      ;; network receive audio
  -D SR_FREQ_PROF=1 -D SR_GAIN=37 -D SR_SQUELCH=10
  -D ABL_MILLIAMPS_DEFAULT=1250
  ;; FEATURES
  ${common_mm.animartrix_build_flags}
  -D WLED_ENABLE_GIF                    ;; 28KB Flash
  -D WLED_ENABLE_PIXART                 ;; 8KB Flash
  -D WLED_ENABLE_PIXELFORGE             ;; 12KB Flash

build_unflags =
  ${env:esp32S3_8MB_PSRAM_M.build_unflags}
  -D WLED_RELEASE_NAME=esp32S3_8MB_M
  -D LEDPIN=21
  ${Speed_Flags.build_unflags}          ;; to override -Os
  ${treyturner.build_unflags_dmx}       ;; skip dmx support
  ${treyturner.build_unflags_skip_ir}   ;; no infrared
  ${treyturner.build_unflags_temp}      ;; no temperature sensor
  ;-D WLED_ENABLE_LOXONE                ;; cruft? uncomment if loxone is enabled for some reason

lib_deps =
  ${esp32s3.lib_deps}
  ${common_mm.lib_deps_S}
  ${common_mm.lib_deps_V4_M}
  ${common_mm.HUB75_lib_deps}
  ${common_mm.animartrix_lib_deps}

lib_ignore =
  ${treyturner.lib_ignore_dmx}
  ${treyturner.lib_ignore_temp}
  ${treyturner.lib_ignore_ir}

board_build.partitions = ${esp32.extreme_partitions}
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216


[env:adafruit_matrix_portal_s3]
extends = esp32_4MB_V4_M_base
platform = ${esp32.platformV4_xp}
platform_packages = ${esp32.platformV4_packages_xp}
board = adafruit_matrixportal_esp32s3_wled
board_build.partitions = tools/partitions-8MB_spiffs-tinyuf2.csv    ;; use original adafruit 8MB tinyUF2 partitioning

build_flags = ${common.build_flags} ${esp32s3.build_flags} -Wno-misleading-indentation -Wno-format-truncation
  ${common_mm.build_flags_S}
  ${common_mm.build_flags_M}
  ${Speed_Flags.build_flags_V4}  ;; -O2 -> optimize for speed instead of size
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  -D WLED_BRAND='"Adafruit"'
  -D WLED_RELEASE_NAME='Adafruit Matrix Portal S3 MM'
  -D SERVERNAME='"Adafruit-Matrix-Portal-S3"'
  ${treyturner.build_flags_hub75}
  ${treyturner.build_flags_psram}
  -D BTNPIN=7                           ;; down button
  -D STATUSLED=17                       ;; onboard LED
  ${treyturner.build_flags_skip_ir}     ;; no infrared
  -D SR_DMTYPE=254                      ;; network receive audio
  -D SR_FREQ_PROF=1 -D SR_GAIN=37 -D SR_SQUELCH=10
  -D ABL_MILLIAMPS_DEFAULT=1250

  ;; FEATURES
  ${common_mm.animartrix_build_flags}
  -D WLED_ENABLE_GIF                    ;; 28KB Flash
  -D WLED_ENABLE_PIXART                 ;; 8KB Flash
  -D WLED_ENABLE_PIXELFORGE             ;; 12KB Flash

build_unflags =
  ${env:esp32S3_8MB_M.build_unflags}    ;; use the same as "normal" S3 buildenv
  ${Speed_Flags.build_unflags}          ;; to override -Os
  ${treyturner.build_unflags_dmx}       ;; skip dmx support
  ${treyturner.build_unflags_temp}      ;; no temperature sensor
  ${treyturner.build_unflags_skip_ir}   ;; no infrared
  ;-D WLED_ENABLE_LOXONE                ;; cruft? uncomment if loxone is enabled for some reason
  -D ARDUINO_USB_CDC_ON_BOOT=1          ;; fix warning: "ARDUINO_USB_CDC_ON_BOOT" redefined; comment out for Serial debug

lib_deps = ${esp32s3.lib_deps} ${common_mm.lib_deps_S}  ;; do not include ${esp32.lib_depsV4} !!!!
  ${common_mm.animartrix_lib_deps}
  ${common_mm.HUB75_lib_deps}

lib_ignore =
  ${treyturner.lib_ignore_dmx}
  ${treyturner.lib_ignore_ir}
  ${treyturner.lib_ignore_temp}

monitor_filters = esp32_exception_decoder


# ESP32-A1S Audio Kit as a dedicated WLED audio analyzer/sender
[env:esp32-a1s_audio_sender]
extends = esp32_4MB_V4_S_base

build_flags =
  ${esp32_4MB_V4_S_base.esp32_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${common_mm.build_disable_sync_interfaces}  ;; strip it down
  ${treyturner.build_flags_skip_ir}
  -D WLED_BRAND='"Ai-Thinker"'
  -D WLED_RELEASE_NAME='Ai-Thinker ESP32-A1S Audio Sender MM'
  -D SERVERNAME='"ESP32-A1S-Audio-Sender"'
  -D PIXEL_COUNTS=1 -D ABL_MILLIAMPS_DEFAULT=1
  -D BTNPIN=36 -D AUDIOPIN=-1 -D RLYPIN=-1
  -D I2S_SDPIN=35 -D I2S_WSPIN=25 -D I2S_CKPIN=27 -D MCLK_PIN=0  ;; I2S line in pins
  -D HW_PIN_SDA=33 -D HW_PIN_SCL=32  ;; I2C
  -D SR_DMTYPE=4 -D SR_FREQ_PROF=1 -D SR_GAIN=37 -D SR_SQUELCH=10  ;; line in settings
  ;; FEATURES
  -D WLED_DISABLE_PARTICLESYSTEM1D
  -D WLED_DISABLE_PARTICLESYSTEM2D
  -D WLED_MAX_BUTTONS=1

build_unflags =
  ${esp32_4MB_V4_S_base.build_unflags}
  ${treyturner.build_unflags_dmx}
  ${treyturner.build_unflags_temp}
  ${treyturner.build_unflags_skip_ir}
  -D USERMOD_AUTO_SAVE
  -D LEDPIN
  -D ABL_MILLIAMPS_DEFAULT
  -D WLED_MAX_BUTTONS

lib_deps = ${esp32_4MB_V4_S_base.esp32_lib_deps}

lib_ignore =
  ${treyturner.lib_ignore_dmx}
  ${treyturner.lib_ignore_ir}
  ${treyturner.lib_ignore_temp}
